### PR TITLE
fix: mink-selenium2-driver:1.3.x-dev no longer exists

### PR DESCRIPTION
**Pull request by alexxed**
Replaced with 1.4.x-dev

https://github.com/minkphp/MinkSelenium2Driver/pull/311

### CODE REVIEW

**Comment by timmillwood** [comment]
This is not a good fix, it'll fail when the branch alias changes to 1.5.x. We should use `~1.3` or `dev-master`.

https://github.com/webflo/drupal-core-require-dev/issues/14

**Comment by alexxed** [comment]
Of course; but it's critical now and I see no other quick fix available right now: 
- 1.3.1 is from 2016, I assume [whoever put it on dev](https://github.com/webflo/drupal-core-require-dev/commit/d97e890ec01181ab219ae64a79266fa4f680c812) wanted something more than that
- 1.4.0 is not yet available on packagist

**Comment by upchuk** [comment]
Related https://github.com/minkphp/MinkSelenium2Driver/issues/313

**Comment by timmillwood** [comment]
if it's critical use `~1.3` or `dev-master`

**Comment by timmillwood** [comment]
IIRC `master-dev` doesn't work, it should be `dev-master`.

**Review by timmillwood — APPROVED** [review]

**Comment by alexxed** [comment]
Right; that works for me. It would be quicker though if https://github.com/minkphp/MinkSelenium2Driver/issues/313 fixes it.

**Comment by upchuk** [comment]
The 1.3 branch will be added back https://github.com/minkphp/MinkSelenium2Driver/issues/313

**Comment by alexxed** [comment]
ok, then let's close this and open when 1.4.0 is available on packagist.

**Comment by BaluErtl** [comment]
> _"The 1.3 branch will be added back [minkphp/MinkSelenium2Driver#313](https://github.com/minkphp/MinkSelenium2Driver/issues/313)"_

Regarding [@stof](https://github.com/stof)'s most recent reply on that thread it doesn't seem like for me that will happen soon on Mink's side:

> _"it would be good if `webflo/drupal-core-require-dev` could fix their mess instead of forcing us to create our own mess to workaround it. You are asking the Mink maintainers to fix a situation they are not responsible for at all here. And anyway, I won't have time to do that right now (and if I had time to work on Mink right now, I would still rather work on preparing things for a next release than working on such workaround)."_

**Comment by alexxed** [comment]
Right, than this still makes sense if a release can happen shortly here.

**Comment by BaluErtl** [comment]
Yesterday Mink's @aik099 was kind enough to re-create 1.3 branch (see [comment](https://github.com/minkphp/MinkSelenium2Driver/issues/313#issuecomment-528518054)), so now I'm a bit unsure whether `webflo/drupal-core-require-dev` package should change to `dev-master` or not?

**Comment by rodrigoaguilera** [comment]
Clearly not, this can be closed

**Comment by greg-1-anderson** [comment]
Existing tags on this project should continue to work. New tags on this project will adopt whatever version constraint appears in Drupal. Hopefully we will be on `^1.4` by the time 8.7.8 comes out. If not, remaining on `1.3.x-dev` is the right thing to do.

**Pull request closed without merging**
